micronaut:
  application:
    name: ociVmAtp
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1.phx.abyhqljrfxs3ec7gff3neal3t65igqajrqltagszyavt45ds7dw4fym7ci5a
    walletPassword: micronaut.1
    username: mnocidemo
    password: "XXXXXXX"
